dist: trusty
language: cpp
os: linux

# Add clang later
compiler: 
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -q update
    - sudo apt-get remove gcc g++
    - sudo apt-get -y install gcc-8 g++-8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
    - sudo update-alternatives --install /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-8 60
    - sudo update-alternatives --install /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-8 60
    - sudo update-alternatives --install /usr/bin/x86_64-linux-gnu-gcc x86_64-linux-gnu-gcc /usr/bin/x86_64-linux-gnu-gcc-8 60 --slave /usr/bin/x86_64-linux-gnu-g++ x86_64-linux-gnu-g++ /usr/bin/x86_64-linux-gnu-g++-8

script:
    - make clean && make all
    - ./bin/test/test_assembler
    - ./bin/test/test_expression
    - ./bin/test/test_source
    - ./bin/test/test_program
    - ./bin/test/test_instruction
    - ./bin/test/test_token
    - ./bin/test/test_eval
